---
- hosts: localhost
  connection: local
  tasks:
    - name: Port Forward Argo CD
      register: port
      command: "kubectl port-forward svc/argocd-server-nodeport 30007:80 -n argocd"
    - debug:
        var: port.stdout_lines