---
- hosts: localhost
  connection: local
  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: linuxrobotgeek	 
        password: Utep123ti*
    - name: Tag and push to docker hub
      docker_image:
        name: tofu-monitoring:latest
        repository: linuxrobotgeek/tofu-monitoring:latest
        push: true
        source: local
    - name: Log out of DockerHub
      community.docker.docker_login:
        state: absent